const express = require('express');
const router = express.Router();
const { GoogleGenAI } = require('@google/genai');

/**
 * POST /api/ai/generate-proposal
 * Expects JSON body: { job_description, job_title, student_skills }
 * Uses @google/genai with 'gemini-2.5-flash' model (free tier)
 * Returns { proposal: "..." }
 */
router.post('/generate-proposal', async (req, res) => {
  try {
    const { job_description, job_title, student_skills } = req.body;

    // Validate required fields
    if (!job_title || typeof job_title !== 'string' || !job_title.trim()) {
      return res.status(400).json({ message: 'job_title is required and cannot be empty.' });
    }

    if (!job_description || typeof job_description !== 'string' || !job_description.trim()) {
      return res.status(400).json({ message: 'job_description is required and cannot be empty.' });
    }

    // Securely read API Key from environment
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey || !apiKey.trim()) {
      return res.status(500).json({
        message: 'GEMINI_API_KEY is not configured on the server. Please set GEMINI_API_KEY in server/.env.'
      });
    }

    // Format student skills
    let formattedSkills = '';
    if (Array.isArray(student_skills)) {
      formattedSkills = student_skills.filter(Boolean).join(', ');
    } else if (typeof student_skills === 'string') {
      formattedSkills = student_skills.trim();
    }

    if (!formattedSkills) {
      formattedSkills = 'Quick learner, enthusiastic college student freelancer with strong academic coursework and hands-on project work.';
    }

    // Prompt instructing Gemini to act as an expert career assistant
    const prompt = `You are an expert career assistant and freelance mentor specializing in college student freelancers.
Write a concise, compelling, and professional 3-paragraph freelance proposal tailored specifically for a college student freelancer applying to the following gig on CampusSkill.

Job Title: ${job_title.trim()}
Job Requirements & Description:
${job_description.trim()}

Student Freelancer Skills & Background:
${formattedSkills}

Proposal Structure Guidelines (EXACTLY 3 PARAGRAPHS):
1. Paragraph 1 (The Hook & Introduction):
   - Enthusiastic opening expressing genuine interest in the specific project.
   - Introduce yourself as an ambitious and dedicated college student freelancer.
   - Demonstrate a clear understanding of what the client is trying to accomplish.

2. Paragraph 2 (The Value & Fit):
   - Highlight how your specific skills and coursework/projects match the client's requirements.
   - Emphasize agility, attention to detail, modern practices, and commitment to delivering clean, high-quality results.

3. Paragraph 3 (Call-to-Action & Closing):
   - Outline communication readiness, flexibility with feedback, and eagerness to discuss milestones and timelines.
   - End with a confident, courteous call-to-action inviting a conversation.

Tone & Formatting Rules:
- Keep the tone professional, humble yet confident, and polished.
- Do NOT use placeholder brackets like [Client Name], [Your Name], or [University Name]. Write seamless, natural text that the student can send directly or easily edit.
- Provide only the proposal text. No conversational preamble, no markdown titles, no bullet points, and no postscript comments.`;

    // Initialize Google GenAI client
    const ai = new GoogleGenAI({ apiKey: apiKey.trim() });

    // Call Gemini 2.5 Flash model
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });

    const proposal = response && response.text ? response.text.trim() : '';

    if (!proposal) {
      return res.status(502).json({
        message: 'No proposal text was generated by Gemini. Please try again.'
      });
    }

    return res.json({ proposal });
  } catch (err) {
    console.error('Gemini proposal generation error:', err);

    const errorMessage = err?.message || '';

    // Handle Rate limits / Quota exhaustion (HTTP 429)
    if (
      err.status === 429 ||
      errorMessage.includes('429') ||
      errorMessage.toLowerCase().includes('quota') ||
      errorMessage.toLowerCase().includes('resource_exhausted')
    ) {
      return res.status(429).json({
        message: 'Gemini free-tier quota or rate limit exceeded. Please wait a moment and try again.'
      });
    }

    // Handle API Key issues (HTTP 401 / 403)
    if (
      err.status === 401 ||
      err.status === 403 ||
      errorMessage.toLowerCase().includes('api key') ||
      errorMessage.toLowerCase().includes('permission_denied')
    ) {
      return res.status(401).json({
        message: 'Authentication failed. Please check that GEMINI_API_KEY is valid.'
      });
    }

    // Generic error fallback
    return res.status(500).json({
      message: 'Failed to generate proposal due to an unexpected AI service error. Please try again later.'
    });
  }
});

module.exports = router;
